version: '3.8'

services:
  # Hyperledger Fabric Services
  ca.org1.trace-herb.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./blockchain/network/crypto-config/peerOrganizations/org1.trace-herb.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.trace-herb.com
    networks:
      - trace-herb-network

  orderer.trace-herb.com:
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./blockchain/network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./blockchain/network/crypto-config/ordererOrganizations/trace-herb.com/orderers/orderer.trace-herb.com/msp:/var/hyperledger/orderer/msp
      - ./blockchain/network/crypto-config/ordererOrganizations/trace-herb.com/orderers/orderer.trace-herb.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - trace-herb-network

  peer0.org1.trace-herb.com:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace-herb_trace-herb-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.trace-herb.com
      - CORE_PEER_ADDRESS=peer0.org1.trace-herb.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.trace-herb.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.trace-herb.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.trace-herb.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./blockchain/network/crypto-config/peerOrganizations/org1.trace-herb.com/peers/peer0.org1.trace-herb.com/msp:/etc/hyperledger/fabric/msp
      - ./blockchain/network/crypto-config/peerOrganizations/org1.trace-herb.com/peers/peer0.org1.trace-herb.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
    depends_on:
      - couchdb0
    networks:
      - trace-herb-network

  # Database Services
  couchdb0:
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - couchdb0_data:/opt/couchdb/data
    networks:
      - trace-herb-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trace-herb-network

  # Application Services
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - couchdb0
      - redis
      - peer0.org1.trace-herb.com
    networks:
      - trace-herb-network

  consumer-portal:
    build:
      context: ./frontend/consumer-portal
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend/consumer-portal:/app
      - /app/node_modules
    networks:
      - trace-herb-network

  dashboard:
    build:
      context: ./frontend/dashboard
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend/dashboard:/app
      - /app/node_modules
    networks:
      - trace-herb-network

volumes:
  couchdb0_data:
  redis_data:

networks:
  trace-herb-network:
    driver: bridge
