version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BLOCKCHAIN_MODE=simulated
      - CORS_ORIGIN=*
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Farmer Portal
  farmer-portal:
    build:
      context: .
      dockerfile: Dockerfile.farmer
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
    restart: unless-stopped
    depends_on:
      - backend

  # Consumer Portal
  consumer-portal:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
    restart: unless-stopped
    depends_on:
      - backend

  # Processor Portal
  processor-portal:
    build:
      context: frontend/processor-portal
      dockerfile: ../../Dockerfile.generic
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
      - PORT=3003
    restart: unless-stopped
    depends_on:
      - backend

  # Lab Portal
  lab-portal:
    build:
      context: frontend/lab-portal
      dockerfile: ../../Dockerfile.generic
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
      - PORT=3004
    restart: unless-stopped
    depends_on:
      - backend

  # Regulator Portal
  regulator-portal:
    build:
      context: frontend/regulator-portal
      dockerfile: ../../Dockerfile.generic
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
      - PORT=3005
    restart: unless-stopped
    depends_on:
      - backend

  # Stakeholder Dashboard
  stakeholder-dashboard:
    build:
      context: frontend/stakeholder-dashboard
      dockerfile: ../../Dockerfile.generic
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
      - PORT=3006
    restart: unless-stopped
    depends_on:
      - backend

  # Management Portal
  management-portal:
    build:
      context: frontend/management-portal
      dockerfile: ../../Dockerfile.generic
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
      - PORT=3007
    restart: unless-stopped
    depends_on:
      - backend

  # Supply Chain Overview
  supply-chain-overview:
    build:
      context: frontend/supply-chain-overview
      dockerfile: ../../Dockerfile.generic
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://trace-herb-backend.railway.app
      - PORT=3008
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend_logs:
  backend_uploads:

networks:
  default:
    name: trace-herb-production
